### ISSUE TITLE
ERROR: FluidPCA - Invalid JSON format

### ISSUE THREAD

**Issue by allholy** [flucoma/flucoma-sc#33]
When I am running a script I am receiving this traceback error:
ERROR: FluidPCA - Invalid JSON format.
I cannot understand where is the exception code that triggered and give us this exception. Could anyone help me?
Thank you in advance!

**Comment by weefuzzy** [comment]
Hi @allholy 

That would happen if `FluidPCA`'s `load` or `read` methods were being called, and the object couldn't make sense of the input (which is a particular JSON format). 

Do you have some code that shows the problem?

**Comment by allholy** [comment]
Thank you for your prompt reply! 
I m trying to connect this extension [https://github.com/mirlca/code](url) in SC3. 
When I am running `MIRLCa.new(path: z, creditsPath: y, modelsPath: x)`, Ι receive this error. 
![Screenshot from 2021-10-31 20-15-51](https://user-images.githubusercontent.com/81262794/139597638-f11b8eed-55d7-4e9a-9eaf-f678b954a019.png)

**Comment by weefuzzy** [comment]
Yes, can confirm: the `pca.json` file in the https://github.com/mirlca/code package doesn't load – it's missing one of the JSON entries it needs('cols'). I've attached a JSON that (I think) fixes it (to go in the `JSON` subfolder of your mirlca installation). 

Happier JSON:  [pca.JSON.zip](https://github.com/flucoma/flucoma-sc/files/7449751/pca.JSON.zip)

Pinging @g-roma @axambo: are these JSON files being  generated from something else? As far as I can see, the `FluidPCA` JSON code has remained untouched since Sept 2020, so I wouldn't expect it to be missing keys (I'll test though...)

**Comment by allholy** [comment]
The error indeed is gone with the `pca.json` file you provided with the 'cols' key. For now it seems to work fine.
Thank you very much!!
