### ISSUE TITLE
Method like `.version` for accessing audio files folder

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-sc#40]
I think this would be easy to implement and a little more elegant for accessing the demo audio files in all the help files. I know this is not the right implementation because there is no `FluCoMa` class, but something like:

```
FluCoMa {
	*audioFilesFolder {
		^(File.realpath(FluidBufPitch.class.filenameSymbol).dirname.withTrailingSlash ++ "../AudioFiles/");
	}
}
```

This suggestion came from an attendee at the CIRMMT workshop and I thought it was a good one. Thoughts?

**Comment by jamesb93** [comment]
So a method on all FluCoMa objects?

I would say this overreaching IMO as its providing syntactical sugar for something that isn't that hard in the first place. I imagine a beginner might see it and wonder how on earth they are getting access to these help files via the object itself, rather than constructing the path on their filesystem themselves.

An alternative might be to provide a helper class  for providing a dictionary of the files.

```js
FluidAudioFiles {
    dump {
        ^PathName(Platform.userExtensionDir++"/FluidCorpusManipulation/AudioFiles/")
    }
}
```

I'm SuperCollidering from the hip here but thats my 2c

**Comment by tedmoore** [comment]
Yup. this is nice. although i'm not sure we always rely on `Platform.userExtensionDir` because there is also `Platform.systemExtensionDir` so routing based on a Fluid class file is actually probably safer.

**Comment by jamesb93** [comment]
Whatever you think is best as you're the expert  in SC not me :) The more I think about it the more it makes sense anyway as Max has the abstraction for working with the audio files directly which emulates the one found strewn across vanilla Max help files. Go for it!

**Comment by tedmoore** [comment]
Ok, a few possibilities about how this might look. Requesting input. @tremblap @jamesb93 @weefuzzy 


1. `FluidExampleFiles()` as standalone class
* use case: `FluidExampleFiles()++"/Nicol-LoopE-M.wav";`


2. `.exampleFiles` like `.version`
* use case: `FluidDataSet.exampleFiles++"/Nicol-LoopE-M.wav";`  (could be any Fluid class, just like `.version`)
 

3. Something else?


4. Let's not do this it's too weird and unnecessary.

**Comment by tremblap** [comment]
what about Fluid.Example.Files.Sounds.Drum.LoopInowCanStand ?

:smile:
(is there a dad joke emoji?)

seriously, it would be great to have it in all CCE but I don't think it is possible.
- in Max, the file names will load because it is packaged
- in Pd it is difficult anyway but i found a way
- so I wonder what is the most SC way

I think that my gut feeling is your number 1, or maybe ```FluidFilesPath``` ... or maybe add to Platform class with a fluidDir method like

```Platform.fluidSounds```

since people are used to reach for that for built-in sound?

**Comment by tedmoore** [comment]
> or maybe add to Platform class with a fluidDir method like
> 
> `Platform.fluidSounds`
> 
> since people are used to reach for that for built-in sound?

This does seem more aligned with how paths are accessed in SC. My only concern is that it would be a bit of a lie since it wouldn't be going through the `Platform` files accessing method. It's a more bottom-up way of accessing.

`Platform` offers `Platform.userExtensionDir`, which isn't too reliable for accessing the FluCoMa files because
1. Someone could have put the extension in `Platform.systemExtensionDir` and 
2. we can't be positive the the folder that contains the FluCoMa extension is actually named the same thing in each user's Extensions folder.

I do like `FluidFilesPath()` better. The class would look like this:

```
FluidFilesFolder {
	*new {
		^"%/../AudioFiles/".format(File.realpath(FluidDataSet.class.filenameSymbol).dirname);
	}
}
```

... so bottom up from the `FluidDataSet` class file, as opposed to top down from the `ExtensionsDir`.

**Comment by tedmoore** [comment]
Made a new commit [c10b879](https://github.com/flucoma/flucoma-sc/commit/c10b87993644635eba2fc59eb1f8c7bce046a7ec) that allows passing the file name in so now any of these are valid:

```
(FluidFilesPath()++"Nicol-LoopE-M.wav").postln;
(FluidFilesPath()+/+"Nicol-LoopE-M.wav").postln;
FluidFilesPath("Nicol-LoopE-M.wav").postln;
FluidFilesPath("/Nicol-LoopE-M.wav").postln;
```
